# 数据库配置
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://${maven_docker.ip}:3306/auth?useUnicode=true&characterEncoding=utf-8
    username: root
    password: Ytsy3113678AB
    driver-class-name: com.mysql.cj.jdbc.Driver
    druid:
      validationQuery: SELECT 1 FROM DUAL
      validationQueryTimeout: 30
      initialSize: 10
      minIdle: 10
      maxActive: 200
      minEvictableIdleTimeMillis: 180000
      testOnBorrow: false
      testWhileIdle: true
      removeAbandoned: true
      removeAbandonedTimeout: 1800
      logAbandoned: true
      poolPreparedStatements: true
      maxOpenPreparedStatements: 100

#  开启flyway
  flyway:
    enabled: true
    url: jdbc:mysql://${maven_docker.ip}:3306/auth?useUnicode=true&characterEncoding=utf-8
    encoding: UTF-8
    user: root
    password: Ytsy3113678AB
    clean-disabled: true
    schemas: auth
  redis:
    host: ${maven_docker.ip}
    port: 6379
    database: 1

# oauth配置
security:
  oauth2:
    resource:
      prefer-token-info: true

# swagger配置
#swagger:
#  enabled: true
#  api-info:
#    appName: 'whyt-seeker'
#    title: 'whyt-seeker'
#    description: '雪影物联网探索者平台'
#    license: ''
#    license-url: ''
#    version: 'v1.0'
#    contact-name: '雪影实业'
#    contact-url: 'http://www.whxiuying.com'
#    contact-email: 'company@whxiuying.com'
#    terms-of-service-url: 'http://www.whxiuying.com'
#    base-package: 'com.xiuying.seeker.auth.web.controller'

# 日志
logging:
  level:
    root: INFO
    org.springframework.security: DEBUG
    com.seeker: DEBUG
