# 数据库配置
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://${maven_docker.ip}:3306/auth?useUnicode=true&characterEncoding=utf-8
    username: root
    password: Ytsy3113678AB
    driver-class-name: com.mysql.cj.jdbc.Driver
    druid:
      validationQuery: SELECT 1 FROM DUAL
      validationQueryTimeout: 30
      initialSize: 10
      minIdle: 10
      maxActive: 200
      minEvictableIdleTimeMillis: 180000
      testOnBorrow: false
      testWhileIdle: true
      removeAbandoned: true
      removeAbandonedTimeout: 1800
      logAbandoned: true
      poolPreparedStatements: true
      maxOpenPreparedStatements: 100

#  开启flyway
  flyway:
    enabled: false
    url: jdbc:mysql://${maven_docker.ip}:3306/auth?useUnicode=true&characterEncoding=utf-8
    encoding: UTF-8
    user: root
    password: Ytsy3113678AB
    clean-disabled: true
    schemas: auth

# oauth配置
security:
  oauth2:
    resource:
      prefer-token-info: true
      user-info-uri: http://127.0.0.1:7001/seeker/api/user/userInfo
    client:
      clientId: admin
      clientSecret: 7a57a5a743894a0e
      access-token-uri: http://127.0.0.1:7777/uaa/oauth/token
      user-authorization-uri: http://127.0.0.1:7777/uaa/oauth/authorize
      grant-type: client_credentials,password

userdetails:
  clients:
  - application: xysy-seeker
    defaultClient: true
    desc: 默认中台userdetails服务配置
#  - application: seeker-member
#    clientId: member
#    desc: 小程序会员userdetails服务配置

feign:
  okhttp:
    enabled: true
    httpclient:
      enabled: true
      maxConnections: 20480
      maxConnectionsPerRoute: 512
      timeToLive: 60
      connectionTimeout: 10000
      userAgent: 'Mozilla/5.0 (Windows NT 6.1; WOW64; rv:37.0) Gecko/20100101 Firefox/37.0'

# 日志
logging:
  level:
    root: INFO
    org.springframework.jdbc: DEBUG
    org.springframework.security: DEBUG
    com.seeker: DEBUG
