# 数据库配置
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://${maven_docker.ip}:3306/auth?useUnicode=true&characterEncoding=utf-8
    username: root
    password: Ytsy3113678AB
    driver-class-name: com.mysql.cj.jdbc.Driver
    druid:
      validationQuery: SELECT 1 FROM DUAL
      validationQueryTimeout: 30
      initialSize: 10
      minIdle: 10
      maxActive: 200
      minEvictableIdleTimeMillis: 180000
      testOnBorrow: false
      testWhileIdle: true
      removeAbandoned: true
      removeAbandonedTimeout: 1800
      logAbandoned: true
      poolPreparedStatements: true
      maxOpenPreparedStatements: 100

#  开启flyway
  flyway:
    enabled: false
    url: jdbc:mysql://${maven_docker.ip}:3306/auth?useUnicode=true&characterEncoding=utf-8
    encoding: UTF-8
    user: root
    password: Ytsy3113678AB
    clean-disabled: true
    schemas: auth

# oauth配置
security:
  oauth2:
    resource:
      prefer-token-info: true
      user-info-uri: http://127.0.0.1:7001/seeker/api/user/userInfo
    client:
      clientId: seeker
      clientSecret: 123456
      access-token-uri: http://127.0.0.1:7777/uaa/oauth/token
      user-authorization-uri: http://127.0.0.1:7777/uaa/oauth/authorize
      #此处必须为授权码方式，否则会造成resource为空
      grant-type: client_credentials
      scope: read,write
      resource-ids: xysy-seeker,seeker-web,seeker-auth-server

userdetails:
  clients:
    - application: xysy-seeker
      defaultClient: true
      contextPath: seeker
      desc: 默认中台userdetails服务配置
#  - application: seeker-member
#    clientId: member
#    desc: 小程序会员userdetails服务配置

feign:
#  client:
#    config:
#      default:
#        connectTimeout: 30000
#        readTimeout: 30000
#        loggerLevel: FULL
  hystrix:
    enabled: true
  httpclient:
    connection-timeout: 30000
  okhttp:
    enabled: true


# 日志
logging:
  level:
    root: INFO
    org.springframework.jdbc: DEBUG
    org.springframework.security: DEBUG
    com.seeker: DEBUG


